<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Toggly.FeatureManagement.Client.Desktop" Version="3.8.0" />
    <Compile Include="../Shared/Showcase.cs" Link="Showcase.cs" />
  </ItemGroup>
</Project>
