version: 2

updates:
  - package-ecosystem: npm
    directory: /javascript-sdk
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      npm-patch-and-minor:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /nextjs-server-sdk
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      npm-patch-and-minor:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: next
        update-types: ["version-update:semver-major"]
      - dependency-name: react
        update-types: ["version-update:semver-major"]
      - dependency-name: react-dom
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /nodejs-fastify-sdk
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /vue-sdk
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
