<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <SampleFramework Condition="'$(SampleFramework)' == ''">net8.0</SampleFramework>
    <TargetFramework>$(SampleFramework)</TargetFramework>
    <AspNetCoreVersion Condition="'$(AspNetCoreVersion)' == ''">8.0.31</AspNetCoreVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Toggly.FeatureManagement.Blazor" Version="0.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(AspNetCoreVersion)" />
  </ItemGroup>

</Project>
