<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SampleFramework Condition="'$(SampleFramework)' == ''">net8.0</SampleFramework>
    <TargetFramework>$(SampleFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <NuGetLockFilePath>packages.$(TargetFramework).lock.json</NuGetLockFilePath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../BlazorSample/BlazorSample.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
