const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const sections = ['home', 'declarative', 'programmatic', 'identity', 'entity', 'filters', 'unique', 'configuration'];
export function page({ section, source, context, order, flags, filters, query }) {
  const selectedPreset = new URLSearchParams(query).get('preset') ?? '';
  const options = (values, selected) => values.map(([value, label]) => `<option value="${escape(value)}"${value === selected ? ' selected' : ''}>${escape(label)}</option>`).join('');
  const role = context.claims?.role ?? 'user';
  const roleValues = [...new Set(['user', 'admin', role])].map(value => [value, value]);
  const link = (path, text) => `<a href="${path}${query ? `?${escape(query)}` : ''}">${text}</a>`;
  const snapshot = names => `<table><tr><th>Flag checklist</th><th>Evaluated for this request</th></tr>${names.map(key => `<tr><td>${key}</td><td>${flags[key] ? 'ON' : 'OFF'}</td></tr>`).join('')}</table>`;
  const content = {
    home: `<p>Explore eight sections using the same flags and presets as the Next.js showcase.</p>${snapshot(Object.keys(flags))}`,
    declarative: `<h2>${flags['new-dashboard'] ? 'Dashboard v2 variant' : 'Classic dashboard variant'}</h2><p>These variants are boolean content branches; the published SDK has no experiment assignment API.</p>${['enabled', 'negate', 'all', 'any', 'beta'].map(name => link(`/gates/${name}`, `${name} HTTP gate`)).join(' · ')}<p>Gates execute the actual Hono featureGate middleware. Disabled routes return 404; beta redirects here.</p>`,
    programmatic: `<p>Read evaluated flags and try a per-call identity override through the published core client.</p>${link('/api/evaluate', 'Evaluate JSON')} · ${link('/api/override', 'Override alice for one call')}`,
    identity: `<p>Identity and claims belong to this request. Demo query/header inputs are not authentication.</p><pre>${escape(JSON.stringify(context, null, 2))}</pre>`,
    entity: `<h2>${flags.ExpressCheckout ? 'Express checkout available' : 'Standard checkout'}</h2><pre>${escape(JSON.stringify(order, null, 2))}</pre><p>Core receives the Order entity on this evaluation. No shared identity or entity is mutated.</p>`,
    filters: `<p>Matching and Non-matching controls exercise the same eleven rows. AlwaysOn and the open TimeWindow stay on; Percentage is sticky and is not prescribed.</p>${snapshot(filters)}<pre>${escape(JSON.stringify(context, null, 2))}</pre>`,
    unique: `<p>Published Hono helpers:</p>${link('/unique/route', 'featureRoutes (API v2)')} · ${link('/unique/wrapped', 'withFeature (enhanced submit)')} · ${link('/api/features', 'featuresHandler snapshot')}<p>featuresHandler returns the SDK global snapshot, not request-evaluated flags. Compare with ${link('/api/evaluate', 'request evaluation')}. Adapter 0.3.0 helpers bind ambient context only; explicit overrides and Order entities use the published core client on the Hono context.</p>`,
    configuration: '<p>Set TOGGLY_APP_KEY and TOGGLY_ENVIRONMENT=Production in .env.local and restart. Empty or ci-placeholder keys use defaults without network. npm run offline uses a loopback fixture and is always labelled. Refresh failure displays unavailable or cached status. See README for exact provisioning and pending live checks.</p>',
  };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${section} · Node Hono SDK Sample</title><style>body{font:17px system-ui;max-width:1080px;margin:2rem auto;padding:0 1rem;color:#172b3a;background:#f6f8fb}nav,aside,main,form{padding:1rem;background:white;border:1px solid #ccd5df;border-radius:10px;margin:1rem 0}nav a{display:inline-block;margin:.4rem}a{color:#0759a3}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:.5rem;border-bottom:1px solid #ccd5df}pre{white-space:pre-wrap;overflow-wrap:anywhere}button,input,select{font:inherit;margin:.3rem;padding:.3rem}aside{border-left:5px solid #d99400}</style></head><body><h1>Node Hono SDK Sample</h1><aside role="status">${escape(source)}</aside><nav aria-label="Sample sections">${sections.map(name => link(`/${name}`, name)).join('')}</nav><form method="get"><label>Preset <select name="preset">${options([['', 'Custom request'], ['matching', 'Matching'], ['non-matching', 'Non-matching']], ['matching', 'non-matching'].includes(selectedPreset) ? selectedPreset : '')}</select></label><button>Apply preset</button></form><form method="get"><label>Identity <input name="identity" value="${escape(context.identity)}"></label><label>Role <select name="role">${options(roleValues, role)}</select></label><label>Order <select name="order">${options([['ord-standard', 'ord-standard'], ['ord-vip', 'ord-vip']], order.key)}</select></label><button>Apply custom request</button></form><main><h2>${section}</h2>${content[section]}</main><footer>Local demonstration only. Never trust query claims or country headers for authorization.</footer></body></html>`;
}
